// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://berqdhodjmjwdgiwiqyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlcnFkaG9kam1qd2RnaXdpcXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODUyMzQsImV4cCI6MjA2NjE2MTIzNH0.550lxIxlBQ1urps9n4TAKFe8itn_PdYyr0DpBcf7aME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);